Install all the dependencies

In [3]:
!pip install langchain chromadb faiss-cpu sentence-transformers pandas langchain-community

Requirement already satisfied: langchain in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (0.3.27)
Requirement already satisfied: chromadb in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (1.1.0)
Requirement already satisfied: faiss-cpu in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (1.12.0)
Requirement already satisfied: sentence-transformers in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (5.1.1)
Requirement already satisfied: pandas in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (2.3.2)
Collecting langchain-community
  Downloading langchain_community-0.3.30-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.72 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain) (0.3.76)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain) (0.3.11)
Requirement already satisfied: langsmith>=0.1.17 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain) (0.4.31)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain) (2.11.9)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain) (2.0.43)
Requirement already satisfied: requests<3,>=2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain) (2.32.5)
Requirement already satisfied: PyYAML>=5.3 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (4.15.0)
Requirement already satisfied: packaging>=23.2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.72->langchain) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from requests<3,>=2->langchain) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from requests<3,>=2->langchain) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from requests<3,>=2->langchain) (2025.8.3)
Requirement already satisfied: greenlet>=1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.4)
Requirement already satisfied: build>=1.0.3 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (1.3.0)
Requirement already satisfied: pybase64>=1.4.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (1.4.2)
Requirement already satisfied: uvicorn>=0.18.3 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.37.0)
Requirement already satisfied: numpy>=1.22.5 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (2.3.3)
Requirement already satisfied: posthog<6.0.0,>=2.4.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (5.4.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (1.23.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (1.37.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (1.37.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (1.37.0)
Requirement already satisfied: tokenizers>=0.13.2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (0.22.1)
Requirement already satisfied: pypika>=0.48.9 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (0.48.9)
Requirement already satisfied: tqdm>=4.65.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (4.67.1)
Requirement already satisfied: overrides>=7.3.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (1.75.1)
Requirement already satisfied: bcrypt>=4.0.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (0.19.2)
Requirement already satisfied: kubernetes>=28.1.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (33.1.0)
Requirement already satisfied: mmh3>=4.0.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (5.2.0)
Requirement already satisfied: orjson>=3.9.12 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (3.11.3)
Requirement already satisfied: httpx>=0.27.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (14.1.0)
Requirement already satisfied: jsonschema>=4.19.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from chromadb) (4.25.1)
Requirement already satisfied: six>=1.5 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.9.0.post0)
Requirement already satisfied: backoff>=1.10.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.9.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from sentence-transformers) (4.56.2)
Requirement already satisfied: torch>=1.11.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from sentence-transformers) (2.8.0)
Requirement already satisfied: scikit-learn in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: scipy in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from sentence-transformers) (1.16.2)
Requirement already satisfied: huggingface-hub>=0.20.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from sentence-transformers) (0.35.1)
Requirement already satisfied: Pillow in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: filelock in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.19.1)
Requirement already satisfied: regex!=2019.12.17 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.9.18)
Requirement already satisfied: safetensors>=0.4.3 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.10)
Requirement already satisfied: pytz>=2020.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community)
  Using cached aiohttp-3.12.15-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Using cached dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.11.0-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Using cached httpx_sse-0.4.1-py3-none-any.whl.metadata (9.4 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.3.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached frozenlist-1.7.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached multidict-6.6.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached propcache-0.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached yarl-1.20.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (73 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Using cached marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langsmith>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from langsmith>=0.1.17->langchain) (0.25.0)
Requirement already satisfied: anyio in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from httpx>=0.27.0->chromadb) (4.11.0)
Requirement already satisfied: httpcore==1.* in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.1)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: pyproject_hooks in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from jsonschema>=4.19.0->chromadb) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from jsonschema>=4.19.0->chromadb) (0.27.1)
Requirement already satisfied: google-auth>=1.0.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from kubernetes>=28.1.0->chromadb) (2.40.3)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests-oauthlib in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: oauthlib>=3.2.2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: durationpy>=0.7 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from rsa<5,>=3.1.4->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.1)
Requirement already satisfied: coloredlogs in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from onnxruntime>=1.14.1->chromadb) (15.0.1)
Requirement already satisfied: flatbuffers in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from onnxruntime>=1.14.1->chromadb) (25.9.23)
Requirement already satisfied: protobuf in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from onnxruntime>=1.14.1->chromadb) (6.32.1)
Requirement already satisfied: sympy in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.0)
Requirement already satisfied: zipp>=3.20 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.70.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.37.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.37.0)
Requirement already satisfied: opentelemetry-proto==1.37.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.37.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.58b0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.58b0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: setuptools in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: networkx in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)

Import all the installed dependencies

In [4]:
import pandas as pd
import numpy as np
from typing import List, Tuple

from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.docstore.document import Document

Load Dataset

In [5]:
url = "https://raw.githubusercontent.com/Bluedata-Consulting/GAAPB01-training-code-base/refs/heads/main/Assignments/assignment2dataset.csv"
df = pd.read_csv(url)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (25, 3)

,course_id,title,description
0,C001,Foundations of Machine Learning,Understand foundational machine learning algor...
1,C002,Deep Learning with TensorFlow and Keras,Explore neural network architectures using Ten...
2,C003,Natural Language Processing Fundamentals,Dive into NLP techniques for processing and un...
3,C004,Computer Vision and Image Processing,Learn the principles of computer vision and im...
4,C005,Reinforcement Learning Basics,Get introduced to reinforcement learning parad...

Prepare Course Documents

In [6]:
# each course becomes a "document" with metadata
docs = []
for idx, row in df.iterrows():
    content = f"{row['title']} - {row['description']}"
    docs.append(Document(page_content=content, metadata={"course_id": row['course_id']}))
    
print("Prepared docs:", len(docs))

Prepared docs: 25

In [7]:
# use HuggingFace model for semantic embeddings
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# build FAISS index
vectorstore = FAISS.from_documents(docs, embedding_model)

print("Vector DB built with", len(docs), "courses.")

/tmp/ipykernel_6760/4018360642.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
/home/zadmin/Desktop/assignments/GenAI_GCP_2/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Vector DB built with 25 courses.

In [8]:
# recommentation function for courses
def recommend_courses(profile: str, completed_ids: List[str], k: int = 5) -> List[Tuple[str, float]]:
    """
    Given a learner profile and completed course IDs, return top-k recommendations.
    """
    # Encode profile as embedding
    results = vectorstore.similarity_search_with_score(profile, k=20)
    
    # Filter out completed courses
    filtered = [(r.metadata["course_id"], score, r.page_content) 
                for r, score in results if r.metadata["course_id"] not in completed_ids]
    
    # Take top-k
    topk = sorted(filtered, key=lambda x: x[1])[:k]
    
    return [(cid, float(score)) for cid, score, _ in topk]

In [9]:
# Sample Input Queries

test_queries = [
    ("I’ve completed the 'Python Programming for Data Science' course and enjoy data visualization. What should I take next?", ["C101"]),
    ("I know Azure basics and want to manage containers and build CI/CD pipelines. Recommend courses.", ["C202"]),
    ("My background is in ML fundamentals; I’d like to specialize in neural networks and production workflows.", ["C303"]),
    ("I want to learn to build and deploy microservices with Kubernetes—what courses fit best?", ["C404"]),
    ("I’m interested in blockchain and smart contracts but have no prior experience. Which courses do you suggest?", []),
]

Create Evaluation and collect results

In [10]:
evaluation_results = []

for profile, completed in test_queries:
    recs = recommend_courses(profile, completed, k=5)
    for cid, score in recs:
        course_title = df[df["course_id"] == cid]["title"].values[0]
        evaluation_results.append({
            "profile": profile,
            "recommended_course_id": cid,
            "recommended_course_title": course_title,
            "similarity_score": score
        })

eval_df = pd.DataFrame(evaluation_results)
eval_df

,profile,recommended_course_id,recommended_course_title,similarity_score
0,I’ve completed the 'Python Programming for Dat...,C016,Python Programming for Data Science,0.481377
1,I’ve completed the 'Python Programming for Dat...,C017,R Programming and Statistical Analysis,0.958742
2,I’ve completed the 'Python Programming for Dat...,C014,Data Visualization with Tableau,1.080086
3,I’ve completed the 'Python Programming for Dat...,C011,Big Data Analytics with Spark,1.149961
4,I’ve completed the 'Python Programming for Dat...,C001,Foundations of Machine Learning,1.207464
5,I know Azure basics and want to manage contain...,C007,Cloud Computing with Azure,0.801474
6,I know Azure basics and want to manage contain...,C009,Containerization with Docker and Kubernetes,0.984642
7,I know Azure basics and want to manage contain...,C008,DevOps Practices and CI/CD,1.066410
8,I know Azure basics and want to manage contain...,C010,APIs and Microservices Architecture,1.213761
9,I know Azure basics and want to manage contain...,C006,Data Engineering on AWS,1.256097
10,My background is in ML fundamentals; I’d like ...,C025,MLOps: Productionizing Machine Learning,0.878867
11,My background is in ML fundamentals; I’d like ...,C002,Deep Learning with TensorFlow and Keras,1.073806
12,My background is in ML fundamentals; I’d like ...,C001,Foundations of Machine Learning,1.193954
13,My background is in ML fundamentals; I’d like ...,C005,Reinforcement Learning Basics,1.263103
14,My background is in ML fundamentals; I’d like ...,C004,Computer Vision and Image Processing,1.314031
15,I want to learn to build and deploy microservi...,C009,Containerization with Docker and Kubernetes,0.603472
16,I want to learn to build and deploy microservi...,C010,APIs and Microservices Architecture,0.916122
17,I want to learn to build and deploy microservi...,C007,Cloud Computing with Azure,1.046142
18,I want to learn to build and deploy microservi...,C025,MLOps: Productionizing Machine Learning,1.152350
19,I want to learn to build and deploy microservi...,C011,Big Data Analytics with Spark,1.270926
20,I’m interested in blockchain and smart contrac...,C023,Blockchain Technology and Smart Contracts,0.735719
21,I’m interested in blockchain and smart contrac...,C010,APIs and Microservices Architecture,1.409493
22,I’m interested in blockchain and smart contrac...,C022,Internet of Things (IoT) Development,1.480578
23,I’m interested in blockchain and smart contrac...,C005,Reinforcement Learning Basics,1.483609
24,I’m interested in blockchain and smart contrac...,C021,Cybersecurity Fundamentals,1.511125

Save evaluation results

In [11]:
eval_df.to_csv("assignment2_recommendations.csv", index=False)
print("Saved results to assignment2_recommendations.csv")

Saved results to assignment2_recommendations.csv